---
- name: Get local IP 
  local_action:
    module: uri
    url: http://checkip.amazonaws.com/
    return_content: yes
  register: ip_lookup

- set_fact:
    local_ip: "{{ ip_lookup.content | regex_replace('\n','') }}"
          
- name: Create the Summit Security Group
  ec2_group:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    region: "{{ region }}" 
    state: present
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ local_ip }}/32"
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 3306
        to_port: 3306
        cidr_ip: 172.31.0.0/16
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  with_items: "{{ ec2_security_groups }}"
  register: aws_sg

- name: Tag the Security Groups with Distinguished Name
  ec2_tag:
    resource: "{{ item.group_id }}"
    region: "{{ region }}"
    state: present
    tags:
      Name: "{{ item.item.name }}"
      Event: "{{ main.eventname }}"
  with_items: "{{ aws_sg.results }}"
  when: aws_sg.changed
