version: "3"
networks:
  main:

services:
  datadog:
    image: datadog/docker-dd-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    environment:
      - API_KEY
      - SD_BACKEND=docker
    networks:
      - main

  frontendredis:
    image: redis
    networks:
      - main

  backendredis:
    build: .
    networks:
      - main