---
- name: Install the MySQL packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: 
    - mysql-server
    - mysql-client
    - python-mysqldb
    - libmysqlclient-dev

- name: Update MySQL root password for all root accounts 
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy the templates to their respestive destination
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root 
    group: root 
    mode: "{{ item.mode | default(644) }}"
  with_items:
    - { src: 'my.cnf.j2', dest: '/etc/mysql/my.cnf' }
    - { src: 'root.cnf.j2', dest: '~/.my.cnf', mode: '600' }
  notify:
    - Restart MySQL

- name: Ensure Anonymous user(s) are not in the database
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
 
- name: Remove the test database
  mysql_db:
    name: test
    state: absent
  notify:
    - Restart MySQL 

- name: Create Datadog User in MySQL
  mysql_user: 
    name: datadog
    host: localhost
    state: present 
    priv: "*.*:REPLICATION CLIENT/*.*:PROCESS/performance_schema.*:SELECT"
    password: datadog

- name: Create Application User in MySQL
  mysql_user: 
    name: "{{ mysql_app_db_user }}"
    host: "%"
    state: present 
    priv: "*.*:ALL"
    password: "{{ mysql_app_db_password }}"

- apt: name=git update_cache=yes

- git: repo=https://github.com/datacharmer/test_db.git dest=~/test_db

- shell: mysql < employees.sql
  args:
    chdir: ~/test_db/

- shell: mysql < test_employees_md5.sql
  args:
    chdir: ~/test_db/ 
  register: testoutput

- debug: msg="{{ testoutput.stdout }}"
