---
- name: Install PHP Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - git
    - php5
    - php5-mcrypt
    - php5-mysql
    - libapache2-mod-php5
  notify:
    - restart apache2

- name: Copy the templates to their respestive destination
  template:
    src: app.ini.j2
    dest: /var/www/html/app.ini
    owner: root 
    group: root 
